name: SunNXT EPG

on:
  workflow_dispatch:

  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Public Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Checkout Private Repo
        uses: actions/checkout@v4
        with:
          repository: vgit-push/sunnxt
          token: ${{ secrets.PRIVATE_REPO_PAT }}
          path: private-src/sunnxt_epg.py

      - name: Install Python Dependencies
        run: |
          pip install requests pytz python-dateutil

      - name: Generate EPG
        run: |
          python private-src/sunnxt_epg.py \
            --days 7 \
            --output epg.xml \
            --gz

      - name: Commit Updated Files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add epg.xml epg.xml.gz

          git diff --cached --quiet && exit 0

          git commit -m "EPG Update $(date -u '+%Y-%m-%d %H:%M UTC')"

      - name: Push Changes
        run: git push
